name: CI

on:
  push:
    branches:
      - master
      - main
      - release/*

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "18.x"
      - run: npm install --force
      - run: npm run build:prod
      - name: Set up Firebase credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > $HOME/firebase-service-account.json
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account.json
